project: 
  type: website

website: 
  page-navigation: true
  title: "Alicia Sabatino" 
  site-url: "https://nmfs-opensci.github.io/NOAA-quarto-simple" 
  repo-url: "https://github.com/nmfs-opensci/NOAA-quarto-simple"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#A73E45"
    logo: "https://aliciasab.github.io/images/alicia_graphic.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://alicias.io
        text: "portfolio"
      - icon: github
        href: https://github.com/aliciasab
        text: "other github"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/add-content.qmd
        text: Add content
      - href: content/customizing.qmd
        text: Customizing
      - href: content/rendering.qmd
        text: Rendering
      - href: content/rmarkdown.Rmd
        text: R Markdown files
      - href: content/code.qmd
        text: Code in your files
      - href: content/acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
